spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    generate-ddl: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
  resources:
    static-locations: classpath:/static/
  devtools:
    restart:
      log-condition-evaluation-delta: false


application:
  security:
    jwt:
      secret-key: b14c3df82436a136d1a18cac4b54d86cc6e4f9c072eb1bbba25c7adacead9005
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web: DEBUG
